//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookLogics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacebookLogics.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap akrav {
            get {
                object obj = ResourceManager.GetObject("akrav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מזל עקרב הוא מזל על כוח ושליטה עצמית.
        ///מזל עקרב ידוע כמזל של הרופא, כי בני עקרב אוהבים לתת לאחרים.
        ///בני מזל עקרב הם לעתים קרובות בעלי יכולת על חושיות, מה שהופך אותם למאבחנים מעולים של מחלות.
        ///עקרבים מגוננים על יקיריהם בבית, אבל אל תנסו להסתיר את הנעשה מעקרב, כי הם רוצים לדעת הכל.
        ///לעקרב יש רשימות אוהב/לא אוהב ברורות מאוד ודואג שכולם ידעו מה הם..
        /// </summary>
        internal static string akrav1 {
            get {
                return ResourceManager.GetString("akrav1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arye {
            get {
                object obj = ResourceManager.GetObject("arye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האריה הוא המלך או המפקד ופוקד היטב.
        ///בן מזל אריה טוב בארגון, לחלק תפקידים ולהיות ישיר.
        ///האריה תמיד מראה התחשבות באחרים ונדיב לאלה שבחוסר.
        ///בן מזל האריה יכול להתאהב מהר מדי ואז יכול להיפגע, אבל מיד אחר כך יהיה מוכן לאהוב שוב..
        /// </summary>
        internal static string arye1 {
            get {
                return ResourceManager.GetString("arye1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap betula {
            get {
                object obj = ResourceManager.GetObject("betula", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש למזל בתולה כוח חד של שימת לב.
        ///בן מזל בתולה הוא מנהל מצוין בדרכים חסכניות וראש צלול.
        ///הבתולה צריך להיזהר לא להיות ביקורתי מדי על אחרים שאינם בעלי כח רצון חזק כשלו.
        ///זה דורש עבודה קשה כדי לזכות באהבה של בן מזל בתולה, אבל מהרגע שזכה, האהבה זוהרת בחום רב כל כך שרק לעיתים רחוקות מתקררת שוב..
        /// </summary>
        internal static string betula1 {
            get {
                return ResourceManager.GetString("betula1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirthdayFactoryBackgroundImage1 {
            get {
                object obj = ResourceManager.GetObject("BirthdayFactoryBackgroundImage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirthdayFactoryBackgroundImage2 {
            get {
                object obj = ResourceManager.GetObject("BirthdayFactoryBackgroundImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirthdayFactoryBackgroundImage3 {
            get {
                object obj = ResourceManager.GetObject("BirthdayFactoryBackgroundImage3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirthdayFactoryBackgroundImage4 {
            get {
                object obj = ResourceManager.GetObject("BirthdayFactoryBackgroundImage4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirthdayFactoryBackgroundImage5 {
            get {
                object obj = ResourceManager.GetObject("BirthdayFactoryBackgroundImage5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirthdayFactoryBackgroundImage6 {
            get {
                object obj = ResourceManager.GetObject("BirthdayFactoryBackgroundImage6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BirthdayFactoryBackgroundImage7 {
            get {
                object obj = ResourceManager.GetObject("BirthdayFactoryBackgroundImage7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dagim {
            get {
                object obj = ResourceManager.GetObject("dagim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בדרך כלל לבן מזל דגים לא ממש איכפת מלעשות כסף, אבל יש לו אידאלים ושאיפות. הדגים אוהבים לחלום, והם לא מעוניינים בתחרות.
        ///בני מזל דגים נמשכים לאמנויות, במיוחד לאומניות הבמה. 
        ///הדגים יכולים להיות נתונים למצבי רוח ואינם ברורים לרוב.
        ///בני מזל דגים מוצאים עצמם מתחברים לדחויים, לחלשים או לאנדרדוגים.
        ///לדגים יכולה להיות יותר מתקופת נישואים אחת בחייהם..
        /// </summary>
        internal static string dagim1 {
            get {
                return ResourceManager.GetString("dagim1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dli {
            get {
                object obj = ResourceManager.GetObject("dli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בן מזל דלי פתוח ובדרך כלל לא מחזיק בדעות קדומות. 
        ///הדלי הוא רגוע וידידותי. 
        ///בן מזל דלי יקשיב וילמד מכל אחד כדי להגיע לאמת. 
        ///לדלי יש תחומי עניין כל כך רבים שלפעמים בנסיון לתפוס מרובה, הוא לא תופס בכלל.
        ///הדליים הינם חברים כנים.
        ///ההגעה לנישואים, עבור הדליים, עשויה להימשך זמן רב שכן הם לא נפתחים בקלות.
        ///
        ///.
        /// </summary>
        internal static string dli1 {
            get {
                return ResourceManager.GetString("dli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gdi {
            get {
                object obj = ResourceManager.GetObject("gdi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בן מזל גדי הוא בדרך כלל דוגל בשמירת מסורת.
        ///הגדי לרוב מתעניין ברווחת הקהילה.
        ///יש לבן מזל גדי שאיפה אצילית וכוח יוצא דופן של הסתגלות.
        ///פעם בכמה זמן הגדי הופך שאפתן מדי כשזה קשור לכספים.
        ///הגדיים הם קצת פלרטטנים. 
        ///כשזה מגיע לנישואים, הגדי מחפש נישואים &quot;מתאימים&quot; וזה בדרך כלל מצליח..
        /// </summary>
        internal static string gdi1 {
            get {
                return ResourceManager.GetString("gdi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap karpada {
            get {
                object obj = ResourceManager.GetObject("karpada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kashat {
            get {
                object obj = ResourceManager.GetObject("kashat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסקרנות של קשת היא באמת לא יודעת שובע והאנרגיה הנפשית תמיד במצב של עירנות.
        ///בן מזל קשת הוא גם מורה וגם תלמיד נפלאים.
        ///הקשת אוהב ידע, אוהב כל מיני סוגים של אנשים, ולעתים קרובות אוהב גם ספורט.
        ///הקשתים הם מאוד כנים ופתוחים עם חברים ואוהבים. 
        ///לפעמים זה נתפס על ידי אחרים כחוסר התחשבות.
        ///לפעמים בן מזל קשת מוצא את זה הכי טוב שלא להתחתן..
        /// </summary>
        internal static string kashat1 {
            get {
                return ResourceManager.GetString("kashat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap moznaim {
            get {
                object obj = ResourceManager.GetObject("moznaim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מזל מאזניים הוא איזון.
        ///מאזניים יעבדו עם ריכוז וירגעו עם מסירות.
        ///חלק מבני מזל מאזניים מחפשים שלמות, שיכול להפוך את החיים ללא קלים למי שחי איתם.
        ///אהבה ונישואין חשובים למאזניים.
        ///אם אתם ברי מזל להתחתן עם בני מאזניים, הבית שלכם יתמלא באמנות ובמוסיקה..
        /// </summary>
        internal static string moznaim1 {
            get {
                return ResourceManager.GetString("moznaim1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhotographerBackgroundImage1 {
            get {
                object obj = ResourceManager.GetObject("PhotographerBackgroundImage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhotographerBackgroundImage2 {
            get {
                object obj = ResourceManager.GetObject("PhotographerBackgroundImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhotographerBackgroundImage3 {
            get {
                object obj = ResourceManager.GetObject("PhotographerBackgroundImage3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhotographerBackgroundImage4 {
            get {
                object obj = ResourceManager.GetObject("PhotographerBackgroundImage4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhotographerBackgroundImage5 {
            get {
                object obj = ResourceManager.GetObject("PhotographerBackgroundImage5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sartan {
            get {
                object obj = ResourceManager.GetObject("sartan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסרטן הוא מאוד סבלני.
        ///הסרטן מרגיש את כל מצבי הרוח במלואם: שמחה, צער, חמלה, האימה ועצב. המשפחה חשובה לבן מזל סרטן.
        ///הסרטן תמיד סולח, אבל אף פעם לא שוכח.
        ///הסרטן יכול לאהוב בחוזקה ולמשך זמן רב. הסרטן הוא נותן, ולכן הלוקחים יכולים לנצלו..
        /// </summary>
        internal static string sartan1 {
            get {
                return ResourceManager.GetString("sartan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shor {
            get {
                object obj = ResourceManager.GetObject("shor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אף אחד לא יותר מתמיד ואיתן ממזל שור.
        ///השור בדרך כלל מצטיין בעבודתו, משום שהוא מבין את החשיבות של שיטה וסדר.
        ///יש לבני מזל שור חוש הומור נפלא, ולעתים קרובות הם משתמשים בהומור שלהם כדי להיות במרכז תשומת לב.
        ///השור הוא לא אגרסיווי, אבל יכול להיות עקשן ומתפנק.
        ///בן מזל שור הוא ידיד נאמן ולויאלי. כמאהבים, השוורים הם חושניים ומלאי אהבה.
        ///השוורים מאוד אוהבים מוסיקה..
        /// </summary>
        internal static string shor1 {
            get {
                return ResourceManager.GetString("shor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tale {
            get {
                object obj = ResourceManager.GetObject("tale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלה אוהב להוביל.
        ///אתגר טוב הוא אושר לטלה.
        ///הטלה עובר את החיים בביטחון והשקפה נלהבת על כל דבר.
        ///הם יכולים להיות חסרי סבלנות ולעתים קרובות לא לסיים את מה שהם מתחילים.
        ///טלאיים הם נדיבים וכנים עם חברים.
        ///כיף בא להם בקלות.
        ///טלה יכול להתאהב במהירות אך להפסיק לאהוב במהירות גבוה יותר..
        /// </summary>
        internal static string tale1 {
            get {
                return ResourceManager.GetString("tale1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap teomim {
            get {
                object obj = ResourceManager.GetObject("teomim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לתאומים יש שפע של אנרגיה רוחנית.
        ///אנרגיה זו חייבת לבוא לידי ביטוי והם לעתים רחוקות סובלים בשתיקה.
        ///בן מזל התאומים מקסים והחיים מעניינים ויפים יותר עם בני המזל בסביבה.
        ///תאומים עלולים לבצע שינויים מהירים בכל היבט של חיים. הם לא יכולים לשאת שעמום.
        ///בן מזל התאומים משתוקק למגוון ולשמחה, וקבלת אהבה מבן תאומים יכולה להיות חוויה מהנה, כל עוד בן התאומים לא נהיה חסר מנוחה..
        /// </summary>
        internal static string teomim1 {
            get {
                return ResourceManager.GetString("teomim1", resourceCulture);
            }
        }
    }
}
